# Generated by Django 4.2.16 on 2026-05-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shahzad Ali', max_length=100)),
                ('tagline', models.CharField(default='Python Backend Developer', max_length=200)),
                ('bio_short', models.TextField(blank=True, help_text='1-2 sentence hero bio')),
                ('bio_detail', models.TextField(blank=True, help_text='Longer about-me paragraph')),
                ('avatar', models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='avatar/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, help_text='Phone number with country code e.g. 923134046317', max_length=30)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True, help_text='Show "Available for opportunities" badge')),
                ('available_label', models.CharField(default='Available for opportunities', max_length=100)),
                ('years_experience', models.CharField(default='2+', max_length=10)),
                ('total_projects', models.CharField(default='13+', max_length=10)),
                ('sites_scraped', models.CharField(default='87+', max_length=10)),
                ('open_to_remote', models.BooleanField(default=True)),
                ('resume_label', models.CharField(default='Download Resume', max_length=50)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
