# Generated by Django 4.2.16 on 2026-05-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_label',
            field=models.CharField(default='Years Exp', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='metric1_icon',
            field=models.CharField(default='bi-lightning-charge-fill', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='metric1_label',
            field=models.CharField(default='Performance Boost', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='metric1_value',
            field=models.CharField(default='40%', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='metric2_icon',
            field=models.CharField(default='bi-speedometer2', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='metric2_label',
            field=models.CharField(default='Faster APIs', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='metric2_value',
            field=models.CharField(default='25%', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='metric3_icon',
            field=models.CharField(default='bi-globe2', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='metric3_label',
            field=models.CharField(default='Sites Scraped', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='metric3_value',
            field=models.CharField(default='87+', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='metric4_icon',
            field=models.CharField(default='bi-clock-history', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='metric4_label',
            field=models.CharField(default='Saved Weekly', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='metric4_value',
            field=models.CharField(default='30min', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects_label',
            field=models.CharField(default='Projects', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='scraped_label',
            field=models.CharField(default='Sites Scraped', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile photo — auto-cropped to square', null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio_detail',
            field=models.TextField(blank=True, help_text='Longer about-me paragraph (HTML from rich editor)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio_short',
            field=models.TextField(blank=True, help_text='1-2 sentence hero bio (plain text)'),
        ),
    ]
