# Generated by Django 4.2.16 on 2026-05-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_experience_label_profile_metric1_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('icon', models.CharField(help_text='Bootstrap Icons class e.g. bi-code-slash', max_length=60)),
                ('position', models.CharField(choices=[('top-right', 'Top Right'), ('top-left', 'Top Left'), ('bottom-left', 'Bottom Left')], default='top-right', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Badge',
                'verbose_name_plural': 'Hero Badges',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=30)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('other', 'Other')], default='other', max_length=10)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('path', models.CharField(default='/', max_length=500)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['visited_at'], name='core_pagevi_visited_5e951c_idx'), models.Index(fields=['ip_address'], name='core_pagevi_ip_addr_037b80_idx'), models.Index(fields=['device_type'], name='core_pagevi_device__d70e25_idx')],
            },
        ),
    ]
